
#ifndef GPIO_PRIVATE_H
#define GPIO_PRIVATE_H

/*      GPIO_BASE_ADDRESSES             */
#define GPIOA_BASE_ADDRESS    0x40004000
#define GPIOB_BASE_ADDRESS    0x40005000
#define GPIOC_BASE_ADDRESS    0x40006000
#define GPIOD_BASE_ADDRESS    0x40007000
#define GPIOE_BASE_ADDRESS    0x40024000
#define GPIOF_BASE_ADDRESS    0x40025000


#define SYSCTL_RCGC2_R          (*((volatile u32 *)0x400FE108))



/*                      GPIO REGISTERS PORTA                              */
#define GPIOA_DATA_BITS_R  ((volatile u32   *) GPIOA_BASE_ADDRESS + 0x000)
#define GPIOA_DATA_R       (*((volatile u32 *) GPIOA_BASE_ADDRESS + 0x3FC))
#define GPIOA_DIR_R        (*((volatile u32 *) GPIOA_BASE_ADDRESS + 0x400))
#define GPIOA_IS_R         (*((volatile u32 *) GPIOA_BASE_ADDRESS + 0x404))
#define GPIOA_IBE_R        (*((volatile u32 *) GPIOA_BASE_ADDRESS + 0x408))
#define GPIOA_IEV_R        (*((volatile u32 *) GPIOA_BASE_ADDRESS + 0x40C))
#define GPIOA_IM_R         (*((volatile u32 *) GPIOA_BASE_ADDRESS + 0x410))
#define GPIOA_RIS_R        (*((volatile u32 *) GPIOA_BASE_ADDRESS + 0x414))
#define GPIOA_MIS_R        (*((volatile u32 *) GPIOA_BASE_ADDRESS + 0x418))
#define GPIOA_ICR_R        (*((volatile u32 *) GPIOA_BASE_ADDRESS + 0x41C))
#define GPIOA_AFSEL_R      (*((volatile u32 *) GPIOA_BASE_ADDRESS + 0x420))
#define GPIOA_DR2R_R       (*((volatile u32 *) GPIOA_BASE_ADDRESS + 0x500))
#define GPIOA_DR4R_R       (*((volatile u32 *) GPIOA_BASE_ADDRESS + 0x504))
#define GPIOA_DR8R_R       (*((volatile u32 *) GPIOA_BASE_ADDRESS + 0x508))
#define GPIOA_ODR_R        (*((volatile u32 *) GPIOA_BASE_ADDRESS + 0x50C))
#define GPIOA_PUR_R        (*((volatile u32 *) GPIOA_BASE_ADDRESS + 0x510))
#define GPIOA_PDR_R        (*((volatile u32 *) GPIOA_BASE_ADDRESS + 0x514))
#define GPIOA_SLR_R        (*((volatile u32 *) GPIOA_BASE_ADDRESS + 0x518))
#define GPIOA_DEN_R        (*((volatile u32 *) GPIOA_BASE_ADDRESS + 0x51C))
#define GPIOA_LOCK_R       (*((volatile u32 *) GPIOA_BASE_ADDRESS + 0x520))
#define GPIOA_CR_R         (*((volatile u32 *) GPIOA_BASE_ADDRESS + 0x524))
#define GPIOA_AMSEL_R      (*((volatile u32 *) GPIOA_BASE_ADDRESS + 0x528))
#define GPIOA_PCTL_R       (*((volatile u32 *) GPIOA_BASE_ADDRESS + 0x52C))
#define GPIOA_ADCCTL_R     (*((volatile u32 *) GPIOA_BASE_ADDRESS + 0x530))
#define GPIOA_DMACTL_R     (*((volatile u32 *) GPIOA_BASE_ADDRESS + 0x534))


/*                      GPIO REGISTERS PORTB                              */
#define GPIOB_DATA_BITS_R  ((volatile u32   *) GPIOB_BASE_ADDRESS + 0x000)
#define GPIOB_DATA_R       (*((volatile u32 *) GPIOB_BASE_ADDRESS + 0x3FC))
#define GPIOB_DIR_R        (*((volatile u32 *) GPIOB_BASE_ADDRESS + 0x400))
#define GPIOB_IS_R         (*((volatile u32 *) GPIOB_BASE_ADDRESS + 0x404))
#define GPIOB_IBE_R        (*((volatile u32 *) GPIOB_BASE_ADDRESS + 0x408))
#define GPIOB_IEV_R        (*((volatile u32 *) GPIOB_BASE_ADDRESS + 0x40C))
#define GPIOB_IM_R         (*((volatile u32 *) GPIOB_BASE_ADDRESS + 0x410))
#define GPIOB_RIS_R        (*((volatile u32 *) GPIOB_BASE_ADDRESS + 0x414))
#define GPIOB_MIS_R        (*((volatile u32 *) GPIOB_BASE_ADDRESS + 0x418))
#define GPIOB_ICR_R        (*((volatile u32 *) GPIOB_BASE_ADDRESS + 0x41C))
#define GPIOB_AFSEL_R      (*((volatile u32 *) GPIOB_BASE_ADDRESS + 0x420))
#define GPIOB_DR2R_R       (*((volatile u32 *) GPIOB_BASE_ADDRESS + 0x500))
#define GPIOB_DR4R_R       (*((volatile u32 *) GPIOB_BASE_ADDRESS + 0x504))
#define GPIOB_DR8R_R       (*((volatile u32 *) GPIOB_BASE_ADDRESS + 0x508))
#define GPIOB_ODR_R        (*((volatile u32 *) GPIOB_BASE_ADDRESS + 0x50C))
#define GPIOB_PUR_R        (*((volatile u32 *) GPIOB_BASE_ADDRESS + 0x510))
#define GPIOB_PDR_R        (*((volatile u32 *) GPIOB_BASE_ADDRESS + 0x514))
#define GPIOB_SLR_R        (*((volatile u32 *) GPIOB_BASE_ADDRESS + 0x518))
#define GPIOB_DEN_R        (*((volatile u32 *) GPIOB_BASE_ADDRESS + 0x51C))
#define GPIOB_LOCK_R       (*((volatile u32 *) GPIOB_BASE_ADDRESS + 0x520))
#define GPIOB_CR_R         (*((volatile u32 *) GPIOB_BASE_ADDRESS + 0x524))
#define GPIOB_AMSEL_R      (*((volatile u32 *) GPIOB_BASE_ADDRESS + 0x528))
#define GPIOB_PCTL_R       (*((volatile u32 *) GPIOB_BASE_ADDRESS + 0x52C))
#define GPIOB_ADCCTL_R     (*((volatile u32 *) GPIOB_BASE_ADDRESS + 0x530))
#define GPIOB_DMACTL_R     (*((volatile u32 *) GPIOB_BASE_ADDRESS + 0x534))

/*                      GPIO REGISTERS PORTC                              */
#define GPIOC_DATA_BITS_R  ((volatile u32   *) GPIOC_BASE_ADDRESS + 0x000)
#define GPIOC_DATA_R       (*((volatile u32 *) GPIOC_BASE_ADDRESS + 0x3FC))
#define GPIOC_DIR_R        (*((volatile u32 *) GPIOC_BASE_ADDRESS + 0x400))
#define GPIOC_IS_R         (*((volatile u32 *) GPIOC_BASE_ADDRESS + 0x404))
#define GPIOC_IBE_R        (*((volatile u32 *) GPIOC_BASE_ADDRESS + 0x408))
#define GPIOC_IEV_R        (*((volatile u32 *) GPIOC_BASE_ADDRESS + 0x40C))
#define GPIOC_IM_R         (*((volatile u32 *) GPIOC_BASE_ADDRESS + 0x410))
#define GPIOC_RIS_R        (*((volatile u32 *) GPIOC_BASE_ADDRESS + 0x414))
#define GPIOC_MIS_R        (*((volatile u32 *) GPIOC_BASE_ADDRESS + 0x418))
#define GPIOC_ICR_R        (*((volatile u32 *) GPIOC_BASE_ADDRESS + 0x41C))
#define GPIOC_AFSEL_R      (*((volatile u32 *) GPIOC_BASE_ADDRESS + 0x420))
#define GPIOC_DR2R_R       (*((volatile u32 *) GPIOC_BASE_ADDRESS + 0x500))
#define GPIOC_DR4R_R       (*((volatile u32 *) GPIOC_BASE_ADDRESS + 0x504))
#define GPIOC_DR8R_R       (*((volatile u32 *) GPIOC_BASE_ADDRESS + 0x508))
#define GPIOC_ODR_R        (*((volatile u32 *) GPIOC_BASE_ADDRESS + 0x50C))
#define GPIOC_PUR_R        (*((volatile u32 *) GPIOC_BASE_ADDRESS + 0x510))
#define GPIOC_PDR_R        (*((volatile u32 *) GPIOC_BASE_ADDRESS + 0x514))
#define GPIOC_SLR_R        (*((volatile u32 *) GPIOC_BASE_ADDRESS + 0x518))
#define GPIOC_DEN_R        (*((volatile u32 *) GPIOC_BASE_ADDRESS + 0x51C))
#define GPIOC_LOCK_R       (*((volatile u32 *) GPIOC_BASE_ADDRESS + 0x520))
#define GPIOC_CR_R         (*((volatile u32 *) GPIOC_BASE_ADDRESS + 0x524))
#define GPIOC_AMSEL_R      (*((volatile u32 *) GPIOC_BASE_ADDRESS + 0x528))
#define GPIOC_PCTL_R       (*((volatile u32 *) GPIOC_BASE_ADDRESS + 0x52C))
#define GPIOC_ADCCTL_R     (*((volatile u32 *) GPIOC_BASE_ADDRESS + 0x530))
#define GPIOC_DMACTL_R     (*((volatile u32 *) GPIOC_BASE_ADDRESS + 0x534))

/*                      GPIO REGISTERS PORTD                              */
#define GPIOD_DATA_BITS_R  ((volatile u32   *) GPIOD_BASE_ADDRESS + 0x000)
#define GPIOD_DATA_R       (*((volatile u32 *) GPIOD_BASE_ADDRESS + 0x3FC))
#define GPIOD_DIR_R        (*((volatile u32 *) GPIOD_BASE_ADDRESS + 0x400))
#define GPIOD_IS_R         (*((volatile u32 *) GPIOD_BASE_ADDRESS + 0x404))
#define GPIOD_IBE_R        (*((volatile u32 *) GPIOD_BASE_ADDRESS + 0x408))
#define GPIOD_IEV_R        (*((volatile u32 *) GPIOD_BASE_ADDRESS + 0x40C))
#define GPIOD_IM_R         (*((volatile u32 *) GPIOD_BASE_ADDRESS + 0x410))
#define GPIOD_RIS_R        (*((volatile u32 *) GPIOD_BASE_ADDRESS + 0x414))
#define GPIOD_MIS_R        (*((volatile u32 *) GPIOD_BASE_ADDRESS + 0x418))
#define GPIOD_ICR_R        (*((volatile u32 *) GPIOD_BASE_ADDRESS + 0x41C))
#define GPIOD_AFSEL_R      (*((volatile u32 *) GPIOD_BASE_ADDRESS + 0x420))
#define GPIOD_DR2R_R       (*((volatile u32 *) GPIOD_BASE_ADDRESS + 0x500))
#define GPIOD_DR4R_R       (*((volatile u32 *) GPIOD_BASE_ADDRESS + 0x504))
#define GPIOD_DR8R_R       (*((volatile u32 *) GPIOD_BASE_ADDRESS + 0x508))
#define GPIOD_ODR_R        (*((volatile u32 *) GPIOD_BASE_ADDRESS + 0x50C))
#define GPIOD_PUR_R        (*((volatile u32 *) GPIOD_BASE_ADDRESS + 0x510))
#define GPIOD_PDR_R        (*((volatile u32 *) GPIOD_BASE_ADDRESS + 0x514))
#define GPIOD_SLR_R        (*((volatile u32 *) GPIOD_BASE_ADDRESS + 0x518))
#define GPIOD_DEN_R        (*((volatile u32 *) GPIOD_BASE_ADDRESS + 0x51C))
#define GPIOD_LOCK_R       (*((volatile u32 *) GPIOD_BASE_ADDRESS + 0x520))
#define GPIOD_CR_R         (*((volatile u32 *) GPIOD_BASE_ADDRESS + 0x524))
#define GPIOD_AMSEL_R      (*((volatile u32 *) GPIOD_BASE_ADDRESS + 0x528))
#define GPIOD_PCTL_R       (*((volatile u32 *) GPIOD_BASE_ADDRESS + 0x52C))
#define GPIOD_ADCCTL_R     (*((volatile u32 *) GPIOD_BASE_ADDRESS + 0x530))
#define GPIOD_DMACTL_R     (*((volatile u32 *) GPIOD_BASE_ADDRESS + 0x534))

/*                      GPIO REGISTERS PORTE                              */
#define GPIOE_DATA_BITS_R  ((volatile u32   *) GPIOE_BASE_ADDRESS + 0x000)
#define GPIOE_DATA_R       (*((volatile u32 *) GPIOE_BASE_ADDRESS + 0x3FC))
#define GPIOE_DIR_R        (*((volatile u32 *) GPIOE_BASE_ADDRESS + 0x400))
#define GPIOE_IS_R         (*((volatile u32 *) GPIOE_BASE_ADDRESS + 0x404))
#define GPIOE_IBE_R        (*((volatile u32 *) GPIOE_BASE_ADDRESS + 0x408))
#define GPIOE_IEV_R        (*((volatile u32 *) GPIOE_BASE_ADDRESS + 0x40C))
#define GPIOE_IM_R         (*((volatile u32 *) GPIOE_BASE_ADDRESS + 0x410))
#define GPIOE_RIS_R        (*((volatile u32 *) GPIOE_BASE_ADDRESS + 0x414))
#define GPIOE_MIS_R        (*((volatile u32 *) GPIOE_BASE_ADDRESS + 0x418))
#define GPIOE_ICR_R        (*((volatile u32 *) GPIOE_BASE_ADDRESS + 0x41C))
#define GPIOE_AFSEL_R      (*((volatile u32 *) GPIOE_BASE_ADDRESS + 0x420))
#define GPIOE_DR2R_R       (*((volatile u32 *) GPIOE_BASE_ADDRESS + 0x500))
#define GPIOE_DR4R_R       (*((volatile u32 *) GPIOE_BASE_ADDRESS + 0x504))
#define GPIOE_DR8R_R       (*((volatile u32 *) GPIOE_BASE_ADDRESS + 0x508))
#define GPIOE_ODR_R        (*((volatile u32 *) GPIOE_BASE_ADDRESS + 0x50C))
#define GPIOE_PUR_R        (*((volatile u32 *) GPIOE_BASE_ADDRESS + 0x510))
#define GPIOE_PDR_R        (*((volatile u32 *) GPIOE_BASE_ADDRESS + 0x514))
#define GPIOE_SLR_R        (*((volatile u32 *) GPIOE_BASE_ADDRESS + 0x518))
#define GPIOE_DEN_R        (*((volatile u32 *) GPIOE_BASE_ADDRESS + 0x51C))
#define GPIOE_LOCK_R       (*((volatile u32 *) GPIOE_BASE_ADDRESS + 0x520))
#define GPIOE_CR_R         (*((volatile u32 *) GPIOE_BASE_ADDRESS + 0x524))
#define GPIOE_AMSEL_R      (*((volatile u32 *) GPIOE_BASE_ADDRESS + 0x528))
#define GPIOE_PCTL_R       (*((volatile u32 *) GPIOE_BASE_ADDRESS + 0x52C))
#define GPIOE_ADCCTL_R     (*((volatile u32 *) GPIOE_BASE_ADDRESS + 0x530))
#define GPIOE_DMACTL_R     (*((volatile u32 *) GPIOE_BASE_ADDRESS + 0x534))

/*                      GPIO REGISTERS PORTD                              */
#define GPIOF_DATA_BITS_R  ((volatile u32   *) 0x40025000)
#define GPIOF_DATA_R       (*((volatile u32 *)  0x400253FC))
#define GPIOF_DIR_R        (*((volatile u32 *)  0x40025400))
#define GPIOF_IS_R         (*((volatile u32 *)  0x40025404))
#define GPIOF_IBE_R        (*((volatile u32 *)  0x40025408))
#define GPIOF_IEV_R        (*((volatile u32 *)  0x4002540C))
#define GPIOF_IM_R         (*((volatile u32 *)  0x40025410))
#define GPIOF_RIS_R        (*((volatile u32 *)  0x40025414))
#define GPIOF_MIS_R        (*((volatile u32 *)  0x40025418))
#define GPIOF_ICR_R        (*((volatile u32 *)  0x4002541C))
#define GPIOF_AFSEL_R      (*((volatile u32 *)  0x40025420))
#define GPIOF_DR2R_R       (*((volatile u32 *)  0x40025500))
#define GPIOF_DR4R_R       (*((volatile u32 *)  0x40025504))
#define GPIOF_DR8R_R       (*((volatile u32 *)  0x40025508))
#define GPIOF_ODR_R        (*((volatile u32 *)  0x4002550C))
#define GPIOF_PUR_R        (*((volatile u32 *)  0x40025510))
#define GPIOF_PDR_R        (*((volatile u32 *)  0x40025514))
#define GPIOF_SLR_R        (*((volatile u32 *)  0x40025518))
#define GPIOF_DEN_R        (*((volatile u32 *)  0x4002551C))
#define GPIOF_LOCK_R       (*((volatile u32 *)  0x40025520))
#define GPIOF_CR_R         (*((volatile u32 *)  0x40025524))
#define GPIOF_AMSEL_R      (*((volatile u32 *)  0x40025528))
#define GPIOF_PCTL_R       (*((volatile u32 *)  0x4002552C))
#define GPIOF_ADCCTL_R     (*((volatile u32 *)  0x40025530))
#define GPIOF_DMACTL_R     (*((volatile u32 *)  0x40025534))




#endif
